// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sholto.Storage;

#nullable disable

namespace Sholto.Storage.Migrations
{
    [DbContext(typeof(SholtoDbContext))]
    [Migration("20260523143923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("BasicAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.HasKey("TrackId");

                    b.ToTable("BpmOverrides");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("KeyAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSecs")
                        .HasColumnType("REAL");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BasicAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.BasicAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BpmOverride")
                        .HasForeignKey("Sholto.Storage.Entities.BpmOverride", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("KeyAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.KeyAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Navigation("BasicAnalysis");

                    b.Navigation("BpmOverride");

                    b.Navigation("KeyAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
