// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sholto.Storage;

#nullable disable

namespace Sholto.Storage.Migrations
{
    [DbContext(typeof(SholtoDbContext))]
    [Migration("20260822224747_AddCratesAndMarkers")]
    partial class AddCratesAndMarkers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("BasicAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.HasKey("TrackId");

                    b.ToTable("BpmOverrides");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Crate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Crates_Name");

                    b.ToTable("Crates");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.CrateTrack", b =>
                {
                    b.Property<int>("CrateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrateId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("CrateTracks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.GridAdjustment", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BpmOverride")
                        .HasColumnType("REAL");

                    b.Property<double>("OffsetSec")
                        .HasColumnType("REAL");

                    b.HasKey("TrackId");

                    b.ToTable("GridAdjustments");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("KeyAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionSecs")
                        .HasColumnType("REAL");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.MarkerLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromMarkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToMarkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromMarkerId");

                    b.HasIndex("ToMarkerId");

                    b.ToTable("MarkerLinks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSecs")
                        .HasColumnType("REAL");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.TrackTag", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TrackTags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BasicAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.BasicAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BpmOverride")
                        .HasForeignKey("Sholto.Storage.Entities.BpmOverride", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.CrateTrack", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Crate", "Crate")
                        .WithMany("CrateTracks")
                        .HasForeignKey("CrateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithMany("CrateTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crate");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.GridAdjustment", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("GridAdjustment")
                        .HasForeignKey("Sholto.Storage.Entities.GridAdjustment", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("KeyAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.KeyAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Marker", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithMany("Markers")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.MarkerLink", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Marker", "FromMarker")
                        .WithMany()
                        .HasForeignKey("FromMarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sholto.Storage.Entities.Marker", "ToMarker")
                        .WithMany()
                        .HasForeignKey("ToMarkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromMarker");

                    b.Navigation("ToMarker");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.TrackTag", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Tag", "Tag")
                        .WithMany("TrackTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithMany("TrackTags")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Crate", b =>
                {
                    b.Navigation("CrateTracks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Tag", b =>
                {
                    b.Navigation("TrackTags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Navigation("BasicAnalysis");

                    b.Navigation("BpmOverride");

                    b.Navigation("CrateTracks");

                    b.Navigation("GridAdjustment");

                    b.Navigation("KeyAnalysis");

                    b.Navigation("Markers");

                    b.Navigation("TrackTags");
                });
#pragma warning restore 612, 618
        }
    }
}
