// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sholto.Storage;

#nullable disable

namespace Sholto.Storage.Migrations
{
    [DbContext(typeof(SholtoDbContext))]
    partial class SholtoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("BasicAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.HasKey("TrackId");

                    b.ToTable("BpmOverrides");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.GridAdjustment", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BpmOverride")
                        .HasColumnType("REAL");

                    b.Property<double>("OffsetSec")
                        .HasColumnType("REAL");

                    b.HasKey("TrackId");

                    b.ToTable("GridAdjustments");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("KeyAnalyses");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSecs")
                        .HasColumnType("REAL");

                    b.Property<long>("FileMtime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.TrackTag", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TrackTags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BasicAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BasicAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.BasicAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.BpmOverride", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("BpmOverride")
                        .HasForeignKey("Sholto.Storage.Entities.BpmOverride", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.GridAdjustment", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("GridAdjustment")
                        .HasForeignKey("Sholto.Storage.Entities.GridAdjustment", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.KeyAnalysisRecord", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithOne("KeyAnalysis")
                        .HasForeignKey("Sholto.Storage.Entities.KeyAnalysisRecord", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.TrackTag", b =>
                {
                    b.HasOne("Sholto.Storage.Entities.Tag", "Tag")
                        .WithMany("TrackTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sholto.Storage.Entities.Track", "Track")
                        .WithMany("TrackTags")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Tag", b =>
                {
                    b.Navigation("TrackTags");
                });

            modelBuilder.Entity("Sholto.Storage.Entities.Track", b =>
                {
                    b.Navigation("BasicAnalysis");

                    b.Navigation("BpmOverride");

                    b.Navigation("GridAdjustment");

                    b.Navigation("KeyAnalysis");

                    b.Navigation("TrackTags");
                });
#pragma warning restore 612, 618
        }
    }
}
