<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="11.3.15" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Sholto.App.ExternalTools" />
    <Using Include="Sholto.TestSupport" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sholto.Interface.MainUI\Sholto.Interface.MainUI.csproj" />
    <ProjectReference Include="..\Sholto.TestSupport\Sholto.TestSupport.csproj" />
  </ItemGroup>

</Project>