<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Sholto.Data/Sholto.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sholto.Interface.Controller.Tests" />
    <InternalsVisibleTo Include="Sholto.Interface.Faceplate.Tests" />
    <InternalsVisibleTo Include="Sholto.Interface.MainUI.Tests" />
  </ItemGroup>

</Project>
