using Avalonia.Media;
using Sholto.Analysis;
using Sholto.Analysis.Harmony;

namespace Sholto.App.Theming;

/// <summary>
/// Per-theme tuning of the Camelot key palette. The 24 chip colors are
/// generated by rotating hue around a 12-position wheel (one per Camelot
/// number), with major keys (B ring) brighter than minor keys (A ring).
/// Themes adjust Saturation / MajorLightness / MinorLightness for their
/// own mood, but <see cref="HueOffset"/> is held at 0 across every bundled
/// theme so the hue family for any given Camelot number stays consistent
/// (e.g. 8A always reads as the same green family; a theme just renders it
/// muted vs vivid). User muscle memory for "key → colour" survives a
/// theme switch.
/// </summary>
public sealed record CamelotPalette(
    double HueOffset,         // degrees; bundled themes always pass 0 — see remarks
    double Saturation,        // 0..1; how vivid the chips are (lower = more muted)
    double MajorLightness,    // 0..1; B ring (major). 0.55 = standard chip brightness
    double MinorLightness,    // 0..1; A ring (minor). Usually lower than Major so relative pairs read as "same hue, different mood"
    IBrush OnChipForeground   // text color drawn on the chip
)
{
    /// <summary>
    /// Distinct, high-contrast colour for a Camelot key chip — same convention DJ
    /// software uses: hue rotates around a 12-position wheel (one per Camelot
    /// number) starting from amber at 8B/8A, so adjacent numbers read as adjacent
    /// on the rainbow; <see cref="HueOffset"/> rotates that start point. Major
    /// keys use <see cref="MajorLightness"/>; minor keys use the lower
    /// <see cref="MinorLightness"/> so relative pairs read as "same hue, different
    /// mood". <paramref name="saturationScale"/> lets a caller dim a chip (e.g.
    /// the library list fades already-played rows to 30% saturation) without
    /// mutating the theme. Malformed <paramref name="camelot"/> codes render white.
    /// </summary>
    public IBrush KeyBrush(string camelot, IHarmonicKeys harmonicKeys, double saturationScale = 1.0)
    {
        if (!harmonicKeys.TryParse(camelot, out int n, out bool isMajor))
            return new SolidColorBrush(Colors.White);
        double hue = (((n - 8) * 30.0 + HueOffset) % 360.0 + 360.0) % 360.0;
        double light = isMajor ? MajorLightness : MinorLightness;
        uint rgb = HslToRgb(hue, Saturation * saturationScale, light);
        return new SolidColorBrush(unchecked((uint)0xFF000000 | rgb));
    }

    private static uint HslToRgb(double h, double s, double l)
    {
        double c = (1 - Math.Abs(2 * l - 1)) * s;
        double hp = h / 60.0;
        double x = c * (1 - Math.Abs(hp % 2 - 1));
        double r1 = 0, g1 = 0, b1 = 0;
        if      (hp < 1) { r1 = c; g1 = x; }
        else if (hp < 2) { r1 = x; g1 = c; }
        else if (hp < 3) { g1 = c; b1 = x; }
        else if (hp < 4) { g1 = x; b1 = c; }
        else if (hp < 5) { r1 = x; b1 = c; }
        else             { r1 = c; b1 = x; }
        double m = l - c / 2;
        byte r = (byte)Math.Clamp((int)Math.Round((r1 + m) * 255), 0, 255);
        byte g = (byte)Math.Clamp((int)Math.Round((g1 + m) * 255), 0, 255);
        byte b = (byte)Math.Clamp((int)Math.Round((b1 + m) * 255), 0, 255);
        return (uint)((r << 16) | (g << 8) | b);
    }
}
