using Avalonia;
using Avalonia.Media;
using Sholto.App.Controls;

namespace Sholto.App.Theming;

/// <summary>
/// Per-theme tuning of the Camelot key palette. The 24 chip colors are
/// generated by rotating hue around a 12-position wheel (one per Camelot
/// number), with major keys (B ring) brighter than minor keys (A ring).
/// Themes adjust Saturation / MajorLightness / MinorLightness for their
/// own mood, but <see cref="HueOffset"/> is held at 0 across every bundled
/// theme so the hue family for any given Camelot number stays consistent
/// (e.g. 8A always reads as the same green family; a theme just renders it
/// muted vs vivid). User muscle memory for "key → colour" survives a
/// theme switch.
/// </summary>
public sealed record CamelotPalette(
    double HueOffset,         // degrees; bundled themes always pass 0 — see remarks
    double Saturation,        // 0..1; how vivid the chips are (lower = more muted)
    double MajorLightness,    // 0..1; B ring (major). 0.55 = standard chip brightness
    double MinorLightness,    // 0..1; A ring (minor). Usually lower than Major so relative pairs read as "same hue, different mood"
    IBrush OnChipForeground   // text color drawn on the chip
);

/// <summary>
/// All UI surface colors. Bind XAML brushes/colors to properties on this so
/// switching <see cref="Themes"/> retones the whole app live.
/// </summary>
public sealed record SholtoTheme(
    string Name,
    IBrush BgDeep,           // window background
    IBrush Surface,          // track list background
    IBrush SurfaceRaised,    // menu bar, deck panel
    IBrush Border,           // panel dividers, vinyl ring
    IBrush Primary,          // DECK A label, primary action
    IBrush Accent,           // BPM number, downbeat highlights
    IBrush AccentBg,         // BPM badge background (semi-transparent of Accent)
    IBrush Mint,             // playhead, needle, "alive" states
    IBrush TextBright,       // primary text
    IBrush TextMuted,        // secondary text
    Color  PlayedFadeColor,  // background color used by the played-half gradient
    WaveformPalette WaveformPalette,
    CamelotPalette CamelotPalette
)
{
    /// <summary>Convenience: the raw Color behind the <see cref="Mint"/> brush, used
    /// where we need a Color (e.g. the WaveformControl's GainOverlayColor for Skia).</summary>
    public Color MintColor =>
        (Mint as SolidColorBrush)?.Color ?? Color.FromArgb(0xC0, 0x34, 0xF0, 0xC6);

    /// <summary>Translucent variant of <see cref="Accent"/> used as the active
    /// loop band over the waveform. Alpha 0x80 (~50 %) is the sweet spot —
    /// solid enough to read clearly against the waveform, soft enough that the
    /// stem colours underneath still show through.</summary>
    public Color LoopBandColor
    {
        get
        {
            var c = (Accent as SolidColorBrush)?.Color ?? Color.FromArgb(0xFF, 0xFF, 0xC7, 0x00);
            return Color.FromArgb(0x80, c.R, c.G, c.B);
        }
    }


    /// <summary>Album-art radial gradient using the theme's primary + accent.</summary>
    public IBrush AlbumArtBrush
    {
        get
        {
            var brush = new RadialGradientBrush
            {
                Center = new RelativePoint(0.35, 0.35, RelativeUnit.Relative),
                GradientOrigin = new RelativePoint(0.35, 0.35, RelativeUnit.Relative),
                RadiusX = new RelativeScalar(0.65, RelativeUnit.Relative),
                RadiusY = new RelativeScalar(0.65, RelativeUnit.Relative),
            };
            var accentColor = (Accent as SolidColorBrush)?.Color ?? Colors.Magenta;
            var primaryColor = (Primary as SolidColorBrush)?.Color ?? Colors.BlueViolet;
            brush.GradientStops.Add(new GradientStop(accentColor, 0.0));
            brush.GradientStops.Add(new GradientStop(primaryColor, 1.0));
            return brush;
        }
    }

    /// <summary>Horizontal gradient fading from PlayedFadeColor on the left to transparent.</summary>
    public IBrush PlayedFadeGradient
    {
        get
        {
            var brush = new LinearGradientBrush
            {
                StartPoint = new RelativePoint(0, 0.5, RelativeUnit.Relative),
                EndPoint   = new RelativePoint(1, 0.5, RelativeUnit.Relative),
            };
            brush.GradientStops.Add(new GradientStop(PlayedFadeColor, 0.0));
            brush.GradientStops.Add(new GradientStop(Color.FromArgb(0xCC, PlayedFadeColor.R, PlayedFadeColor.G, PlayedFadeColor.B), 0.6));
            brush.GradientStops.Add(new GradientStop(Color.FromArgb(0x00, PlayedFadeColor.R, PlayedFadeColor.G, PlayedFadeColor.B), 1.0));
            return brush;
        }
    }
}

/// <summary>
/// Theme registry. Themes are no longer hard-coded — they're loaded from JSON
/// files at startup via <see cref="SholtoThemeJson.LoadAll"/>: bundled themes
/// from <c>avares://Sholto.App/Themes/</c> plus optional user themes from
/// <c>~/.config/opendj/themes/</c>. The named static accessors (Classic,
/// Serato, …) survive for compile-time callers and just look up by name in
/// <see cref="All"/>. If a theme is missing (e.g. user deleted its JSON), the
/// accessor falls back to the first available theme so the UI never crashes.
/// </summary>
public static class Themes
{
    public static IReadOnlyList<SholtoTheme> All { get; } = SholtoThemeJson.LoadAll();

    private static SholtoTheme ByName(string name)
    {
        foreach (var t in All)
            if (string.Equals(t.Name, name, StringComparison.OrdinalIgnoreCase))
                return t;
        // Missing theme — fall back so the UI doesn't NRE during startup.
        return All.Count > 0 ? All[0] : throw new InvalidOperationException("No themes loaded");
    }

    public static SholtoTheme Classic           => ByName("Classic");
    public static SholtoTheme Serato            => ByName("Serato");
    public static SholtoTheme FrontLineAssembly => ByName("Front Line Assembly");
    public static SholtoTheme SilenceGroove     => ByName("Silence Groove");
    public static SholtoTheme JeremySoule       => ByName("Jeremy Soule");
    public static SholtoTheme DrabMajesty       => ByName("Drab Majesty");
    public static SholtoTheme SubFocus          => ByName("Sub Focus");
    public static SholtoTheme TypeONegative     => ByName("Type O Negative");
    public static SholtoTheme BirthdayMassacre  => ByName("Birthday Massacre");
    public static SholtoTheme BoardsOfCanada    => ByName("Boards of Canada");
    public static SholtoTheme Pantera           => ByName("Pantera");
}
