using Avalonia;
using Avalonia.Media;
using Sholto.App.Controls;

namespace Sholto.App.Theming;

/// <summary>
/// Per-theme tuning of the Camelot key palette. The 24 chip colors are
/// generated by rotating hue around a 12-position wheel (one per Camelot
/// number), with major keys (B ring) brighter than minor keys (A ring).
/// Themes shift the rainbow's warmth / saturation / mood by tweaking these
/// four numbers — preserves the "adjacent keys = adjacent hues" invariant
/// that's the whole point of Camelot coloring.
/// </summary>
public sealed record CamelotPalette(
    double HueOffset,         // degrees; shifts the start of the rainbow (warmer/cooler)
    double Saturation,        // 0..1; how vivid the chips are (lower = more muted)
    double MajorLightness,    // 0..1; B ring (major). 0.55 = standard chip brightness
    double MinorLightness,    // 0..1; A ring (minor). Usually lower than Major so relative pairs read as "same hue, different mood"
    IBrush OnChipForeground   // text color drawn on the chip
);

/// <summary>
/// All UI surface colors. Bind XAML brushes/colors to properties on this so
/// switching <see cref="Themes"/> retones the whole app live.
/// </summary>
public sealed record SholtoTheme(
    string Name,
    IBrush BgDeep,           // window background
    IBrush Surface,          // track list background
    IBrush SurfaceRaised,    // menu bar, deck panel
    IBrush Border,           // panel dividers, vinyl ring
    IBrush Primary,          // DECK A label, primary action
    IBrush Accent,           // BPM number, downbeat highlights
    IBrush AccentBg,         // BPM badge background (semi-transparent of Accent)
    IBrush Mint,             // playhead, needle, "alive" states
    IBrush TextBright,       // primary text
    IBrush TextMuted,        // secondary text
    Color  PlayedFadeColor,  // background color used by the played-half gradient
    WaveformPalette WaveformPalette,
    CamelotPalette CamelotPalette
)
{
    /// <summary>Convenience: the raw Color behind the <see cref="Mint"/> brush, used
    /// where we need a Color (e.g. the WaveformControl's GainOverlayColor for Skia).</summary>
    public Color MintColor =>
        (Mint as SolidColorBrush)?.Color ?? Color.FromArgb(0xC0, 0x34, 0xF0, 0xC6);

    /// <summary>Album-art radial gradient using the theme's primary + accent.</summary>
    public IBrush AlbumArtBrush
    {
        get
        {
            var brush = new RadialGradientBrush
            {
                Center = new RelativePoint(0.35, 0.35, RelativeUnit.Relative),
                GradientOrigin = new RelativePoint(0.35, 0.35, RelativeUnit.Relative),
                RadiusX = new RelativeScalar(0.65, RelativeUnit.Relative),
                RadiusY = new RelativeScalar(0.65, RelativeUnit.Relative),
            };
            var accentColor = (Accent as SolidColorBrush)?.Color ?? Colors.Magenta;
            var primaryColor = (Primary as SolidColorBrush)?.Color ?? Colors.BlueViolet;
            brush.GradientStops.Add(new GradientStop(accentColor, 0.0));
            brush.GradientStops.Add(new GradientStop(primaryColor, 1.0));
            return brush;
        }
    }

    /// <summary>Horizontal gradient fading from PlayedFadeColor on the left to transparent.</summary>
    public IBrush PlayedFadeGradient
    {
        get
        {
            var brush = new LinearGradientBrush
            {
                StartPoint = new RelativePoint(0, 0.5, RelativeUnit.Relative),
                EndPoint   = new RelativePoint(1, 0.5, RelativeUnit.Relative),
            };
            brush.GradientStops.Add(new GradientStop(PlayedFadeColor, 0.0));
            brush.GradientStops.Add(new GradientStop(Color.FromArgb(0xCC, PlayedFadeColor.R, PlayedFadeColor.G, PlayedFadeColor.B), 0.6));
            brush.GradientStops.Add(new GradientStop(Color.FromArgb(0x00, PlayedFadeColor.R, PlayedFadeColor.G, PlayedFadeColor.B), 1.0));
            return brush;
        }
    }
}

public static class Themes
{
    private static IBrush B(string hex) => new SolidColorBrush(Color.Parse(hex));
    private static Color  C(string hex) => Color.Parse(hex);

    public static SholtoTheme Classic { get; } = new(
        Name: "Classic",
        BgDeep:        B("#111111"),
        Surface:       B("#1A1A1A"),
        SurfaceRaised: B("#222222"),
        Border:        B("#333333"),
        Primary:       B("#00FFCC"),
        Accent:        B("#FFC700"),
        AccentBg:      B("#33FFC700"),
        Mint:          B("#FFFFFF"),
        TextBright:    B("#EEEEEE"),
        TextMuted:     B("#888888"),
        PlayedFadeColor: C("#111111"),
        WaveformPalette: WaveformPalette.Bands,
        // Classic — the original baseline. Vivid rainbow, deep navy text.
        CamelotPalette: new(HueOffset: 0, Saturation: 0.78,
                            MajorLightness: 0.55, MinorLightness: 0.42,
                            OnChipForeground: B("#101820"))
    );


    public static SholtoTheme Serato { get; } = new(
        Name: "Serato",
        BgDeep:        B("#0F0F0F"),
        Surface:       B("#161616"),
        SurfaceRaised: B("#1E1E1E"),
        Border:        B("#3D3D3D"),
        Primary:       B("#FF3D3D"),
        Accent:        B("#3D8BFF"),
        AccentBg:      B("#333D8BFF"),
        Mint:          B("#3DFF7A"),
        TextBright:    B("#F2F2F2"),
        TextMuted:     B("#909090"),
        PlayedFadeColor: C("#0F0F0F"),
        WaveformPalette: WaveformPalette.Hot,
        // Serato — punchy, high-sat rainbow to match the red/blue accents.
        CamelotPalette: new(HueOffset: 0, Saturation: 0.82,
                            MajorLightness: 0.55, MinorLightness: 0.42,
                            OnChipForeground: B("#0F0F0F"))
    );

    /// <summary>Smoke — late-night vinyl-bar moody. Warm charcoal browns with
    /// whiskey amber and candle gold. No neon; this one feels lit by candles.</summary>
    public static SholtoTheme Smoke { get; } = new(
        Name: "Smoke",
        BgDeep:        B("#1C1917"),
        Surface:       B("#2A2522"),
        SurfaceRaised: B("#332C28"),
        Border:        B("#463C36"),
        Primary:       B("#A88468"),
        Accent:        B("#F2C879"),
        AccentBg:      B("#33F2C879"),
        Mint:          B("#D4A574"),
        TextBright:    B("#F0E5D2"),
        TextMuted:     B("#8A7B6E"),
        PlayedFadeColor: C("#1C1917"),
        WaveformPalette: WaveformPalette.Smoke,
        // Smoke — warm shift (amber/whiskey lean), desaturated so the rainbow
        // reads as candle-lit rather than neon. Dark chip text matches the bg.
        CamelotPalette: new(HueOffset: 15, Saturation: 0.45,
                            MajorLightness: 0.54, MinorLightness: 0.40,
                            OnChipForeground: B("#1C1917"))
    );

    /// <summary>Silence Groove — cyberpunk-rain neon. Deep navy with hot magenta
    /// and electric cyan. Crowd-pleaser dev-theme aesthetic. Named after the
    /// liquid-DnB / atmospheric producer.</summary>
    public static SholtoTheme SilenceGroove { get; } = new(
        Name: "Silence Groove",
        BgDeep:        B("#0F172A"),
        Surface:       B("#1A2238"),
        SurfaceRaised: B("#222C46"),
        Border:        B("#2F3B57"),
        Primary:       B("#7AA2F7"),
        Accent:        B("#FF7AC6"),
        AccentBg:      B("#33FF7AC6"),
        Mint:          B("#7AE6FF"),
        TextBright:    B("#E2E7F5"),
        TextMuted:     B("#7C89B8"),
        PlayedFadeColor: C("#0F172A"),
        WaveformPalette: WaveformPalette.Plasma,
        // Silence Groove — slight cool shift, high saturation. Rainbow leans into
        // the magenta/cyan neon energy the rest of the theme is built around.
        CamelotPalette: new(HueOffset: -10, Saturation: 0.80,
                            MajorLightness: 0.58, MinorLightness: 0.44,
                            OnChipForeground: B("#0F172A"))
    );

    /// <summary>Catppuccin Mocha — soft pastel peach / mauve / sky on warm dark.
    /// The cosy dev-community favourite; easy on the eyes for long sessions.</summary>
    public static SholtoTheme CatppuccinMocha { get; } = new(
        Name: "Catppuccin Mocha",
        BgDeep:        B("#1E1E2E"),
        Surface:       B("#28283C"),
        SurfaceRaised: B("#313244"),
        Border:        B("#45475A"),
        Primary:       B("#CBA6F7"),
        Accent:        B("#F5C2E7"),
        AccentBg:      B("#33F5C2E7"),
        Mint:          B("#94E2D5"),
        TextBright:    B("#CDD6F4"),
        TextMuted:     B("#7F849C"),
        PlayedFadeColor: C("#1E1E2E"),
        WaveformPalette: WaveformPalette.Plasma,
        // Catppuccin Mocha — pastel. Lower saturation + higher lightness so the
        // chips match the cosy soft-color aesthetic instead of clashing with it.
        CamelotPalette: new(HueOffset: 0, Saturation: 0.50,
                            MajorLightness: 0.70, MinorLightness: 0.55,
                            OnChipForeground: B("#1E1E2E"))
    );

    /// <summary>Drab Majesty — gothic darkwave. Slate-blue surfaces with frost
    /// and aurora-violet accents. Reads more "studio" than "club". Named after
    /// the gothic post-punk duo.</summary>
    public static SholtoTheme DrabMajesty { get; } = new(
        Name: "Drab Majesty",
        BgDeep:        B("#1E293B"),
        Surface:       B("#243044"),
        SurfaceRaised: B("#293548"),
        Border:        B("#3B4860"),
        Primary:       B("#88C0D0"),
        Accent:        B("#B48EAD"),
        AccentBg:      B("#33B48EAD"),
        Mint:          B("#A3BE8C"),
        TextBright:    B("#ECEFF4"),
        TextMuted:     B("#7B8A9E"),
        PlayedFadeColor: C("#1E293B"),
        WaveformPalette: WaveformPalette.Glacier,
        // Drab Majesty — cool shift, low saturation. Reads more "studio" than "club".
        CamelotPalette: new(HueOffset: -15, Saturation: 0.55,
                            MajorLightness: 0.58, MinorLightness: 0.45,
                            OnChipForeground: B("#1E293B"))
    );

    /// <summary>Bloodmoon — high-drama. Near-black carbon with crimson and bone.
    /// Aggressive / metal / dark-techno energy.</summary>
    public static SholtoTheme Bloodmoon { get; } = new(
        Name: "Bloodmoon",
        BgDeep:        B("#0A0606"),
        Surface:       B("#140B0B"),
        SurfaceRaised: B("#1A0E0E"),
        Border:        B("#2E1414"),
        Primary:       B("#C8324D"),
        Accent:        B("#E8A54B"),
        AccentBg:      B("#33C8324D"),
        Mint:          B("#F5E6D8"),
        TextBright:    B("#F2E8DC"),
        TextMuted:     B("#8A6F65"),
        PlayedFadeColor: C("#0A0606"),
        WaveformPalette: WaveformPalette.Bloodmoon,
        // Bloodmoon — warm shift, dimmed and brooding. Bone-coloured chip text
        // because the chips themselves run dark in this theme.
        CamelotPalette: new(HueOffset: -20, Saturation: 0.55,
                            MajorLightness: 0.50, MinorLightness: 0.36,
                            OnChipForeground: B("#F2E8DC"))
    );

    /// <summary>Type O Negative — gothic doom metal aesthetic. Deep forest
    /// green on near-black charcoal. Named after the Brooklyn band — same
    /// album-cover palette of greens-on-blacks with bone-coloured text.</summary>
    public static SholtoTheme TypeONegative { get; } = new(
        Name: "Type O Negative",
        BgDeep:        B("#050A07"),
        Surface:       B("#0B130E"),
        SurfaceRaised: B("#0F1A13"),
        Border:        B("#1F3526"),
        Primary:       B("#2C7A47"),
        Accent:        B("#4FA66E"),
        AccentBg:      B("#334FA66E"),
        Mint:          B("#7FC894"),
        TextBright:    B("#D8E6DC"),
        TextMuted:     B("#6A8472"),
        PlayedFadeColor: C("#050A07"),
        WaveformPalette: WaveformPalette.Bloodmoon,
        // Type O Negative — green-shifted hues, low sat, dark lightness for
        // that "ritual candlelight on green velvet" mood. Bone text on chips
        // matches the band's typeface.
        CamelotPalette: new(HueOffset: 60, Saturation: 0.50,
                            MajorLightness: 0.45, MinorLightness: 0.34,
                            OnChipForeground: B("#D8E6DC"))
    );

    /// <summary>Birthday Massacre — black with vivid magenta / violet. Named
    /// after the Toronto darksynth-rock band. Aggressive nightclub-meets-
    /// horror-cartoon aesthetic.</summary>
    public static SholtoTheme BirthdayMassacre { get; } = new(
        Name: "Birthday Massacre",
        BgDeep:        B("#0A0612"),
        Surface:       B("#150B22"),
        SurfaceRaised: B("#1E1133"),
        Border:        B("#3D2858"),
        Primary:       B("#B85FD8"),
        Accent:        B("#E83FB4"),
        AccentBg:      B("#33E83FB4"),
        Mint:          B("#D8AAFF"),
        TextBright:    B("#EEDFFA"),
        TextMuted:     B("#806B95"),
        PlayedFadeColor: C("#0A0612"),
        WaveformPalette: WaveformPalette.Plasma,
        // Birthday Massacre — purple-shifted, vivid saturation. Chips run hot
        // pink/violet → bright; the rainbow rotates so it leans into the
        // theme's magenta/purple territory instead of competing with it.
        CamelotPalette: new(HueOffset: 200, Saturation: 0.70,
                            MajorLightness: 0.58, MinorLightness: 0.45,
                            OnChipForeground: B("#1E1133"))
    );

    public static IReadOnlyList<SholtoTheme> All { get; } =
        [Classic, Serato, Smoke, SilenceGroove, CatppuccinMocha, DrabMajesty,
         Bloodmoon, TypeONegative, BirthdayMassacre];
}
